# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_ref_clk.xdc

# Block Designs: bd/mbdesign/mbdesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign || ORIG_REF_NAME==mbdesign} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_microblaze_0_0/mbdesign_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_microblaze_0_0 || ORIG_REF_NAME==mbdesign_microblaze_0_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_dlmb_v10_0/mbdesign_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_dlmb_v10_0 || ORIG_REF_NAME==mbdesign_dlmb_v10_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_ilmb_v10_0/mbdesign_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_ilmb_v10_0 || ORIG_REF_NAME==mbdesign_ilmb_v10_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_dlmb_bram_if_cntlr_0/mbdesign_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mbdesign_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_ilmb_bram_if_cntlr_0/mbdesign_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mbdesign_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_lmb_bram_0/mbdesign_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_lmb_bram_0 || ORIG_REF_NAME==mbdesign_lmb_bram_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_xbar_0/mbdesign_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_xbar_0 || ORIG_REF_NAME==mbdesign_xbar_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_microblaze_0_axi_periph_0/mbdesign_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mbdesign_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_microblaze_0_axi_intc_0/mbdesign_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mbdesign_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_microblaze_0_xlconcat_0/mbdesign_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mbdesign_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_mdm_1_0/mbdesign_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_mdm_1_0 || ORIG_REF_NAME==mbdesign_mdm_1_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_clk_wiz_1_0/mbdesign_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_clk_wiz_1_0 || ORIG_REF_NAME==mbdesign_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_rst_clk_wiz_1_100M_0/mbdesign_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mbdesign_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_mig_7series_0_0/mbdesign_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_mig_7series_0_0 || ORIG_REF_NAME==mbdesign_mig_7series_0_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_mii_to_rmii_0_0/mbdesign_mii_to_rmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_mii_to_rmii_0_0 || ORIG_REF_NAME==mbdesign_mii_to_rmii_0_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_axi_uartlite_0_0/mbdesign_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_axi_uartlite_0_0 || ORIG_REF_NAME==mbdesign_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_axi_ethernetlite_0_0/mbdesign_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_axi_ethernetlite_0_0 || ORIG_REF_NAME==mbdesign_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_axi_timer_0_0/mbdesign_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_axi_timer_0_0 || ORIG_REF_NAME==mbdesign_axi_timer_0_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_axi_smc_0/mbdesign_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_axi_smc_0 || ORIG_REF_NAME==mbdesign_axi_smc_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_rst_mig_7series_0_81M_0/mbdesign_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==mbdesign_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/mbdesign/ip/mbdesign_ecemptcamip_0_0/mbdesign_ecemptcamip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbdesign_ecemptcamip_0_0 || ORIG_REF_NAME==mbdesign_ecemptcamip_0_0} -quiet] -quiet

# XDC: bd/mbdesign/mbdesign_ooc.xdc
