@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Jan 22 15:35:57 +0530 2024
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 0ba07a13509647e7b855f24bc8f30daa --incr --debug typical --relax --mt 2 -L microblaze_v11_0_1 -L xil_defaultlib -L lmb_v10_v3_0_9 -L lmb_bram_if_cntlr_v4_0_16 -L blk_mem_gen_v8_4_3 -L generic_baseblocks_v2_1_0 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_19 -L fifo_generator_v13_2_4 -L axi_data_fifo_v2_1_18 -L axi_crossbar_v2_1_20 -L axi_lite_ipif_v3_0_4 -L axi_intc_v4_1_13 -L xlconcat_v2_1_3 -L mdm_v3_2_16 -L lib_cdc_v1_0_2 -L proc_sys_reset_v5_0_13 -L mii_to_rmii_v2_0_21 -L lib_pkg_v1_0_2 -L lib_srl_fifo_v1_0_2 -L axi_uartlite_v2_0_23 -L lib_bmg_v1_0_12 -L lib_fifo_v1_0_13 -L axi_ethernetlite_v3_0_17 -L axi_timer_v2_0_21 -L xlconstant_v1_1_6 -L smartconnect_v1_0 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot mbdesign_wrapper_behav xil_defaultlib.mbdesign_wrapper xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 0ba07a13509647e7b855f24bc8f30daa --incr --debug typical --relax --mt 2 -L microblaze_v11_0_1 -L xil_defaultlib -L lmb_v10_v3_0_9 -L lmb_bram_if_cntlr_v4_0_16 -L blk_mem_gen_v8_4_3 -L generic_baseblocks_v2_1_0 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_19 -L fifo_generator_v13_2_4 -L axi_data_fifo_v2_1_18 -L axi_crossbar_v2_1_20 -L axi_lite_ipif_v3_0_4 -L axi_intc_v4_1_13 -L xlconcat_v2_1_3 -L mdm_v3_2_16 -L lib_cdc_v1_0_2 -L proc_sys_reset_v5_0_13 -L mii_to_rmii_v2_0_21 -L lib_pkg_v1_0_2 -L lib_srl_fifo_v1_0_2 -L axi_uartlite_v2_0_23 -L lib_bmg_v1_0_12 -L lib_fifo_v1_0_13 -L axi_ethernetlite_v3_0_17 -L axi_timer_v2_0_21 -L xlconstant_v1_1_6 -L smartconnect_v1_0 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot mbdesign_wrapper_behav xil_defaultlib.mbdesign_wrapper xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
